import { describe, expect, it } from "vitest";

import { extractGithubFeedback, isMosaicAuthoredPayload } from "../packages/intake/src/adapters/github.adapter.js";

describe("GitHub intake adapter", () => {
  it("detects Mosaic-authored issue payloads", () => {
    expect(isMosaicAuthoredPayload({
      sender: { login: "mosaicfeedback[bot]" },
      repository: { full_name: "owner/repo" },
      issue: {
        body: "Generated by Mosaic",
        user: { login: "mosaicfeedback[bot]" }
      }
    })).toBe(true);
  });

  it("detects Mosaic-authored comment payloads", () => {
    expect(isMosaicAuthoredPayload({
      sender: { login: "app/mosaicfeedback" },
      repository: { full_name: "owner/repo" },
      issue: {
        body: "User issue",
        user: { login: "someone" }
      },
      comment: {
        body: "@mosaic fix this",
        user: { login: "app/mosaicfeedback" }
      }
    })).toBe(true);
  });

  it("allows user-authored payloads through classification", () => {
    const payload = {
      action: "opened",
      sender: { login: "liamkernan" },
      repository: { full_name: "liamkernan/sampleformosaic" },
      issue: {
        body: "Please add the missing article pages",
        user: { login: "liamkernan" },
        html_url: "https://github.com/liamkernan/sampleformosaic/issues/12",
        number: 12
      }
    };

    expect(isMosaicAuthoredPayload(payload)).toBe(false);
    expect(extractGithubFeedback(payload)).toMatchObject({
      source: "github_issue",
      normalizedInput: {
        repoFullName: "liamkernan/sampleformosaic",
        senderIdentifier: "liamkernan"
      }
    });
  });
});
