import { Redis } from "ioredis";

import { getEnv, logger, RateLimitError, type PRPayload, type RepoContext, type RepoConfig } from "@mosaic/core";
import { getOctokit } from "@mosaic/github-app";

interface PRCreationOptions {
  draft?: boolean;
  linkedIssueNumber?: number;
}

function sanitizeSlug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s/-]/g, "")
    .trim()
    .replace(/[\s/]+/g, "-")
    .replace(/-+/g, "-");
}

function buildBranchName(category: string, summary: string, feedbackId: string, branchPrefix: string): string {
  const prefix = branchPrefix.endsWith("/") ? branchPrefix : `${branchPrefix}/`;
  const suffix = sanitizeSlug(`${category}-${summary}`).slice(0, 48);
  return `${prefix}${suffix}-${feedbackId.slice(0, 6)}`;
}

function truncateTitle(summary: string): string {
  return `[Mosaic] ${summary}`.slice(0, 72);
}

function createPrBody(payload: PRPayload, options: PRCreationOptions): string {
  const issueReference = options.linkedIssueNumber
    ? `### Linked Issue
${options.draft ? "Refs" : "Closes"} #${options.linkedIssueNumber}

`
    : "";

  return `## Automated PR from User Feedback

**Source:** ${payload.feedbackItem.source}
**Category:** ${payload.feedbackItem.category}
**Complexity:** ${payload.feedbackItem.complexity}
**Confidence:** ${payload.feedbackItem.confidence}

### Original Feedback
> ${payload.feedbackItem.rawContent.slice(0, 500).replace(/\n/g, "\n> ")}

${issueReference}### Changes Made
${payload.changes.map((change) => `- \`${change.filePath}\`: ${change.explanation}`).join("\n")}

---
*This PR was automatically generated by [Mosaic](https://github.com/YOUR_USERNAME/mosaic). Review carefully before merging.*
*To configure Mosaic, see the repo's \`mosaic.config.yml\`.*`;
}

const redis = new Redis(getEnv().REDIS_URL, { maxRetriesPerRequest: null });

async function enforcePrRateLimit(repoFullName: string): Promise<void> {
  const bucket = new Date().toISOString().slice(0, 13);
  const key = `pr-rate:${repoFullName}:${bucket}`;
  const total = await redis.incr(key);
  if (total === 1) {
    await redis.expire(key, 3600);
  }

  if (total > getEnv().PRS_PER_HOUR) {
    throw new RateLimitError(`PR rate limit exceeded for ${repoFullName}`);
  }
}

export class PRCreator {
  async createPR(payload: PRPayload, repoContext: RepoContext, repoConfig: RepoConfig, options: PRCreationOptions = {}): Promise<string> {
    await enforcePrRateLimit(payload.repoFullName);

    const octokit = await getOctokit(repoContext.installationId);
    const [owner, repo] = payload.repoFullName.split("/");
    const branchName = buildBranchName(
      payload.feedbackItem.category,
      payload.feedbackItem.summary,
      payload.feedbackItem.id,
      repoConfig.branchPrefix
    );

    const refResponse = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${repoContext.defaultBranch}`
    });
    const baseCommit = await octokit.rest.git.getCommit({
      owner,
      repo,
      commit_sha: refResponse.data.object.sha
    });

    const blobs = await Promise.all(
      payload.changes.map((change) =>
        octokit.rest.git.createBlob({
          owner,
          repo,
          content: change.modifiedContent,
          encoding: "utf-8"
        })
      )
    );

    const tree = await octokit.rest.git.createTree({
      owner,
      repo,
      base_tree: baseCommit.data.tree.sha,
      tree: payload.changes.map((change, index) => ({
        path: change.filePath,
        mode: "100644",
        type: "blob",
        sha: blobs[index].data.sha
      }))
    });

    const commit = await octokit.rest.git.createCommit({
      owner,
      repo,
      message: truncateTitle(payload.feedbackItem.summary),
      tree: tree.data.sha,
      parents: [refResponse.data.object.sha]
    });

    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: commit.data.sha
    });

    const pr = await octokit.rest.pulls.create({
      owner,
      repo,
      title: truncateTitle(payload.feedbackItem.summary),
      body: createPrBody(
        {
          ...payload,
          branchName,
          title: truncateTitle(payload.feedbackItem.summary)
        },
        options
      ),
      head: branchName,
      base: repoContext.defaultBranch,
      draft: options.draft ?? false
    });

    if (repoConfig.reviewers && repoConfig.reviewers.length > 0) {
      try {
        await octokit.rest.pulls.requestReviewers({
          owner,
          repo,
          pull_number: pr.data.number,
          reviewers: repoConfig.reviewers
        });
      } catch (error) {
        logger.warn({ err: error, repo: payload.repoFullName, pullNumber: pr.data.number }, "Failed to request reviewers");
      }
    }

    try {
      await octokit.rest.issues.addLabels({
        owner,
        repo,
        issue_number: pr.data.number,
        labels: ["mosaic", "automated", payload.feedbackItem.category]
      });
    } catch (error) {
      logger.warn({ err: error, repo: payload.repoFullName, pullNumber: pr.data.number }, "Failed to add PR labels");
    }

    return pr.data.html_url;
  }
}
